variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  PYTHON_VERSION: "3.10"

stages:
  - quality
  - test
  - docs
  - deploy

.base:
  image: python:$PYTHON_VERSION
  cache:
      key:
        files:
          - pyproject.toml
        prefix: $CI_JOB_NAME
      paths:
        - .cache/pip
        - .tox
  interruptible: true
  before_script:
    - pip install tox

quality:lint:
  extends: .base
  stage: quality
  script:
    - tox -e lint

test:unittest:
  extends: .base
  stage: test
  image: python:$PYTHON_VER
  script:
    - tox -e $ENV
    - tox -e coverage-report
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura.xml
  parallel:
    matrix:
      - ENV: py39
        PYTHON_VER: "3.9"
      - ENV: py310
        PYTHON_VER: "3.10"
      - ENV: py311
        PYTHON_VER: "3.11"
      - ENV: py312
        PYTHON_VER: "3.12"
      - ENV: py313
        PYTHON_VER: "3.13"

docs:docs:
  extends: .base
  stage: docs
  script:
    - tox -e docs

docs:changelog:
  extends: .base
  stage: docs
  script:
    - tox -e changelog

docs:description:
  extends: .base
  stage: docs
  script:
    - tox -e pypi-description

deploy:publish_docs:
  extends: .base
  stage: deploy
  script:
    - tox -e docs
    - mv docs/_build/html html
    # - mv docs/_build/rinoh pdf
  artifacts:
    name: "docs-$CI_COMMIT_REF_NAME"
    paths:
      - html
      # - pdf/mlnext.pdf
  only:
    - main
    - tags

deploy:build:
  extends: .base
  stage: deploy
  artifacts:
    name: dist
    paths:
      - ./dist
    expire_in: 1h
  script:
    - tox -e build
  only:
    - main
    - tags

deploy:release-private:
  image: python:$PYTHON_VERSION
  stage: deploy
  needs:
    - deploy:build
  before_script:
    - pip install twine
  script:
    - python -m twine upload --verbose --skip-existing dist/*
  only:
    - tags

deploy:release-public-pypi:
  image: python:$PYTHON_VERSION
  stage: deploy
  needs:
    - deploy:build
  before_script:
    - pip install twine
  script:
    - >
      python
      -m twine upload
      --verbose
      --skip-existing
      --repository-url ${PYPI_REPOSITORY_URL}
      --cert ${PYPI_CERT}
      -u ${PYPI_USER}
      -p ${PYPI_TOKEN}
      dist/*
  only:
    - pypi-release
    - tags
  allow_failure: true
