stages:
  - quality
  - test
  - documentation
  - deploy

image: python:3.8-alpine
before_script:
  - pip install tox

lint:
  stage: quality
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  script:
    - tox -e lint
  cache:
    paths:
      - ${PRE_COMMIT_HOME}

pytest:
  stage: test
  script:
    - tox -e py38

docs:
  stage: test
  script:
    - tox -e docs

coverage:
  stage: documentation
  script:
    - tox -e coverage-report
  artifacts:
    reports:
      cobertura: coverage.xml

changelog:
  stage: documentation
  script:
    - tox -e changelog

description:
  stage: documentation
  script:
    - tox -e pypi-description

release:
  stage: deploy
  before_script:
    - pip install twine
  script:
    - python -m build
    - python -m twine upload --verbose --skip-existing dist/*
  only:
    - dev
    - master
    - tags
