stages:
  - quality
  - test
  - documentation
  - deploy

image: python:3.8
before_script:
  - pip install tox

lint:
  stage: quality
  script:
    - tox -e lint

unittest:
  stage: test
  script:
    - tox -e py38
    - tox -e coverage-report
  artifacts:
    reports:
      cobertura: coverage.xml

docs:
  stage: documentation
  variables:
    GITLABPAGES: 1
  script:
    - tox -e docs

changelog:
  stage: documentation
  script:
    - tox -e changelog

description:
  stage: documentation
  script:
    - tox -e pypi-description

release:
  stage: deploy
  before_script:
    - pip install twine
  script:
    - python -m build
    - python -m twine upload --verbose --skip-existing dist/*
  only:
    - dev
    - master
    - tags
