# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: double-quote-string-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: (^tests/helpers/)|(^tests/.*/FIX.*)
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]

  -   repo: https://github.com/asottile/pyupgrade
      rev: v3.19.0
      hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.14.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'
    hooks:
      -   id: mypy
          exclude: '^tests/'
          additional_dependencies:
            - "numpy"
            - "pydantic"
            - "types-PyYAML"
            - "pandas-stubs"
